#!/bin/bash


if [[ -z "$(which COSMO)" ]] ; then
	echo "COSMO not found, do you maybe need to do conda activate cosmo?" >&2
	exit 1
fi

COSMO -D 1 -d 2 -F 5.0 -f 10.0 -o Wildtype_Control1.csv 'gi|126697566|ref|NC_009089.1|' 4290252  " $(pwd)\ Wildtype_Control1.bam"/ " $(pwd)/NC_009089.1.gff"

