version: 2

jobs:
  build:
    working_directory: ~/operon
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout

      - restore_cache:
          keys:
            - tb_operon_detection-{{ checksum "requirements.txt" }}
      - run:
          command: |
            conda config --add channels conda-forge
            conda config --add channels bioconda
            conda install --file requirements.txt

      - save_cache:
          key: tb_operon_detection-{{ checksum "requirements.txt" }}
          paths:
            - /opt/conda

      - run: python -m pytest

      - store_test_results:
          path: test/results
      - store_artifacts:
          path: test/results
          destination: tr1